name: Docker Build/Publish Image

on:
  schedule:
  - cron: "0 2 * * 0"
  push:
    branches: [ main ]

jobs:   
  build:    
    runs-on: ubuntu-latest    
    env:      
      DOCKER_REGISTRY: docker.io      
      DOCKER_IMAGE: lukasdotcom/website      
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm64,linux/arm/v7,linux/amd64                   
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v3             
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Prepare      
      if: success()      
      id: prepare      
      run: |  
        echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
        echo "docker_image=${DOCKER_REGISTRY}/${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
        echo "version=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

    - name: Docker Login      
      if: success()      
      run: |        
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin              
    - name: Run Buildx (push image)      
      if: success()      
      run: |        
        docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag ${{ steps.prepare.outputs.docker_image }}:latest --tag ${{ steps.prepare.outputs.docker_image }}:$(date --rfc-3339=date) --file Dockerfile --push .
