name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --platform=linux/arm64 --file Dockerfile --tag lukasdotcom/website:$(date +%s)
        docker build . --platform=linux/arm/v7 --file Dockerfile --tag lukasdotcom/website:$(date +%s)
